# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# database init, supports mysql too
petclinic.database: hsqldb
spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql

# JPA
spring.jpa.hibernate.ddl-auto: none

# Logging
logging.level.org.springframework: INFO

# Sleuth
spring.sleuth.sampler.percentage: "1.0"
spring.zipkin.baseUrl: http://tracing-server:9441/

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
