# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# database init, supports mysql too
petclinic.database: mysql
spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql

spring.datasource.url=jdbc:mysql://petclinic-mysql/app
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.datasource.driverClassName=com.mysql.jdbc.Driver


# JPA
spring.jpa.hibernate.ddl-auto: none

# Logging
logging.level.org.springframework: INFO

# Sleuth
spring.sleuth.sampler.percentage: "1.0"
spring.zipkin.baseUrl: http://tracing-server:9411/

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
